[ 2024-10-04 19:00:36,270 ] 97 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.102:5000
[ 2024-10-04 19:00:36,270 ] 97 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[ 2024-10-04 19:00:40,873 ] 97 werkzeug - INFO - 127.0.0.1 - - [04/Oct/2024 19:00:40] "GET /predictdata HTTP/1.1" 200 -
[ 2024-10-04 19:01:00,886 ] 838 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "D:\ExcelR\ML\Project\src\pipeline\predict_pipeline.py", line 13, in predict
    model_path=os.path.join("artifacts","model.pkl")
               ^^
NameError: name 'os' is not defined. Did you forget to import 'os'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ExcelR\ML\Project\myenv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ExcelR\ML\Project\myenv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ExcelR\ML\Project\myenv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ExcelR\ML\Project\myenv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ExcelR\ML\Project\app.py", line 40, in predict_datapoint
    results=predict_pipeline.predict(pred_df)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ExcelR\ML\Project\src\pipeline\predict_pipeline.py", line 24, in predict
    raise CustomException(e,sys)
src.exception.CustomException: Error occured in python script name [D:\ExcelR\ML\Project\src\pipeline\predict_pipeline.py] line number [13] error message[name 'os' is not defined]
[ 2024-10-04 19:01:00,889 ] 97 werkzeug - INFO - 127.0.0.1 - - [04/Oct/2024 19:01:00] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
[ 2024-10-04 19:01:47,000 ] 97 werkzeug - INFO - 127.0.0.1 - - [04/Oct/2024 19:01:47] "GET / HTTP/1.1" 200 -
[ 2024-10-04 19:02:10,313 ] 97 werkzeug - INFO - 127.0.0.1 - - [04/Oct/2024 19:02:10] "GET / HTTP/1.1" 200 -
[ 2024-10-04 19:02:12,418 ] 97 werkzeug - INFO - 127.0.0.1 - - [04/Oct/2024 19:02:12] "GET / HTTP/1.1" 200 -
